name: Prod React CI/CD

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install

    - name: Build
      env:
        REACT_APP_BASE_URL: https://api.cookingacademy.qa/api/1.0
        CI: false

      run: npm run build
    
    - name: Configure SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }} 

    - name: Deploy
      env:
        REMOTE_IP: ${{ secrets.PROD_REMOTE_IP }}
        FRONT_PROJECT_PATH: ${{ secrets.FRONT_PROJECT_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$REMOTE_IP "rm -fr $FRONT_PROJECT_PATH/*"
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/* ubuntu@$REMOTE_IP:$FRONT_PROJECT_PATH